
import __ASTRO_IMAGE_IMPORT_1QOnYt from "./resource/langgraph-n8n-make-hero.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Flanggraph-n8n-make%2Fen.md";
import __ASTRO_IMAGE_IMPORT_1Sd2XF from "./resource/langgraph-n8n-make-hero.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Flanggraph-n8n-make%2Fzh.md";
import __ASTRO_IMAGE_IMPORT_l6fPG from "./resource/make-context-aware-job-agent-part1-01-overview.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fmake-job-agent-part-1%2Fen.md";
import __ASTRO_IMAGE_IMPORT_mtTOS from "./resource/make-context-aware-job-agent-part1-01-overview.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fmake-job-agent-part-1%2Fzh.md";
import __ASTRO_IMAGE_IMPORT_Z1S1PWQ from "./resource/make-context-aware-job-agent-part1-02-intake-context.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fmake-job-agent-part-1%2Fen.md";
import __ASTRO_IMAGE_IMPORT_Z1QDbXE from "./resource/make-context-aware-job-agent-part1-02-intake-context.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fmake-job-agent-part-1%2Fzh.md";
import __ASTRO_IMAGE_IMPORT_Z1nHH6N from "./resource/make-context-aware-job-agent-part1-03-router-lanes.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fmake-job-agent-part-1%2Fen.md";
import __ASTRO_IMAGE_IMPORT_Z1mk37B from "./resource/make-context-aware-job-agent-part1-03-router-lanes.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fmake-job-agent-part-1%2Fzh.md";
import __ASTRO_IMAGE_IMPORT_ZzoWdY from "./resource/make-context-aware-job-agent-part1-04-job-scraping.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fmake-job-agent-part-1%2Fen.md";
import __ASTRO_IMAGE_IMPORT_Zy1ieM from "./resource/make-context-aware-job-agent-part1-04-job-scraping.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fmake-job-agent-part-1%2Fzh.md";
export default new Map([["./resource/langgraph-n8n-make-hero.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Flanggraph-n8n-make%2Fen.md", __ASTRO_IMAGE_IMPORT_1QOnYt], ["./resource/langgraph-n8n-make-hero.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Flanggraph-n8n-make%2Fzh.md", __ASTRO_IMAGE_IMPORT_1Sd2XF], ["./resource/make-context-aware-job-agent-part1-01-overview.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fmake-job-agent-part-1%2Fen.md", __ASTRO_IMAGE_IMPORT_l6fPG], ["./resource/make-context-aware-job-agent-part1-01-overview.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fmake-job-agent-part-1%2Fzh.md", __ASTRO_IMAGE_IMPORT_mtTOS], ["./resource/make-context-aware-job-agent-part1-02-intake-context.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fmake-job-agent-part-1%2Fen.md", __ASTRO_IMAGE_IMPORT_Z1S1PWQ], ["./resource/make-context-aware-job-agent-part1-02-intake-context.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fmake-job-agent-part-1%2Fzh.md", __ASTRO_IMAGE_IMPORT_Z1QDbXE], ["./resource/make-context-aware-job-agent-part1-03-router-lanes.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fmake-job-agent-part-1%2Fen.md", __ASTRO_IMAGE_IMPORT_Z1nHH6N], ["./resource/make-context-aware-job-agent-part1-03-router-lanes.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fmake-job-agent-part-1%2Fzh.md", __ASTRO_IMAGE_IMPORT_Z1mk37B], ["./resource/make-context-aware-job-agent-part1-04-job-scraping.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fmake-job-agent-part-1%2Fen.md", __ASTRO_IMAGE_IMPORT_ZzoWdY], ["./resource/make-context-aware-job-agent-part1-04-job-scraping.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fmake-job-agent-part-1%2Fzh.md", __ASTRO_IMAGE_IMPORT_Zy1ieM]]);
		